## path to input h5 files, this folder must contain fast5_pass and fast5_skip
## This will also be where the output files will be located
directory: "/home/nmhd/projects/matt/16S_4_dec"
barcodefile: "ONP_Barcodes.txt"
lineageremove: "Chloroplast-Mitochondria-unknown-Archaea-Eukaryota"
