## path to input h5 files, this folder must contain fast5_pass and fast5_skip
## This will also be where the output files will be located
directory: "/mypool/projects/steve_frese/16s_project"
database: "/mypool/projects/steve_frese/mothur_db"
#directory: "/home/nmhd/projects/matt/16S_4_dec"
#database: "/home/nmhd/databases/nanopore"
lineageremove: "Chloroplast-Mitochondria-unknown-Archaea-Eukaryota"
